if (window.localStorage.getItem('lang') == "cn") {
    $(function () {
        $('.faq').bootstrapTable({
            data: faq_cn
        });
    });
} else {
    $(function () {
        $('.faq').bootstrapTable({
            data: faq
        });
    });
}

const faq = [
    {"Question":"Token value is generated by channel s system itself?","Answer":"Yes. The token value and the token lifetime can be set by the channel system."},
    {"Question":"Is the usage of this API : userinfo?","Answer":"Can be used when the channel want to recharge the user ‘s money."},
    {"Question":"Can batch query the user info?","Answer":"No, our API only support query single user info."},
    {"Question":"Can batch recharge more user?","Answer":"No."},
    {"Question":"How about username limitation?","Answer":"There is no length limitation, but 25 letter is recommended. Username could only be composed of lowercase letter , number, and specific symbol(eg. @ _)"},
    {"Question":"How to set nickname?","Answer":"Nickname could be set at the first time of login. the length isn't recommended to be longer than 7 letter."},
    {"Question":"How to restrict the user from sub channel login into game?","Answer":"Channel web api just return the ‘Channel is under maintenance’ status code when detect the user is from sub channel."},
    {"Question":"How to add new user into eBET server?","Answer":"As soon as first user first time login then eBet server will automatically create the user Or use api/syncuser to create user."},
    {"Question":"How to handle the network problem when calling the recharge API?","Answer":"Our suggestion is to use the recharge status API or user info API to check the current user’s money."},
    {"Question":"Does it support for frequent recharge?","Answer":"No, suggest 1-2 minute interval unless ebet will return busy status and will failure."},
    {"Question":"How many type of login method?","Answer":"Normal login: The user enters the username and password on eBET's web or app, and eBET provides the channel for verification. Token login: The user logsin to the channel platform, click the Token login link provided by the channel to enter the eBET web, and eBET will provide the channel for verification. AppLinks login: The user logsin to the channel platform,click AppLink provided by the channel to log in and open the eBET app, and eBET will provide the channel for verification. OAuth login:  When the channel wants to use the eBET app directly but wants to use its own login page, this login method can be used. Provide link to login page and implement related api."},
    {"Question":"How to know which subchannel user belong to?","Answer":"please query by userInfo api."},
    {"Question":"For the new user, how to recharge money for them and syns the deposit in channel and eBet?","Answer":"Every times channel get the eBet confirmation at the same time eBet server sent the current user amounts, at theater time system can merge amount of charge in or out. Use api/syncuser to create user then call the api/recharge to recharge transfer money to eBET wallet."},
    {"Question":"Is it the same ABC123 username and abc123 username?","Answer":"eBet server only store Lowercase character username. So it is the same."},
    {"Question":"Channel and sub Channel name can have same username?","Answer":"No, because not able to differentiate the user is from which sub channel. For avoid conflict create username concatenation with channel prefix name."},
    {"Question":"How to decide the sub channel ID?","Answer":"No, is auto generated by system."},
    {"Question":"How to get the channel ID?","Answer":"After eBet admin success help to open the channel, then the channel ID information will be included in integration information."},
    {"Question":"How to create sub channel?","Answer":"Please create subchannel in our back office."},
    {"Question":"Do need a prefix for username?","Answer":"It’s up to channel, if and only if web api has passed that is OK."},
    {"Question":"Is possible to get user bet history by specific interval time?","Answer":"Yes, we recommend that fifteen-minute interval between two queries and 1000 records per query."},
    {"Question":"How to check the sub channel user bet history only?","Answer":"Set the sub channel parameter value."},
    {"Question":"Is it real time and sync?","Answer":"Yes, but it is recommended to query after 2-3 minutes."},
    {"Question":"Is there a garbled username when searching for user betting records?","Answer":"The garbled user name is the data of the test user, and it needs to be filtered when obtaining the betting record."},
    {"Question":"How to recharge user’s money?","Answer":"If want to add money, then set the money parameter as positive value such as 100.0. If want to reduce money, then set the money parameter as negative value such as -100.0."},
    ];

const faq_cn = [
    {"Question":"Token是渠道自己自定义？","Answer":"是的，渠道可以自定义 Token 的值，还有设置 Token 的生命周期。"},
    {"Question":"userinfo在什么情况下使用？","Answer":"当渠道系统为用户充值，转进转出金额时，可以现调此 API 功能来看到当前用户的金额。"},
    {"Question":"可以批量查询多个用户的信息？","Answer":"不能，目前的 API 功能只提供查询单一的用户信息。"},
    {"Question":"可以批量为多个用户充值？","Answer":"不能。"},
    {"Question":"用户名规定长度，值和限制？","Answer":"并无上限限制，但建议使用 25 字符，可以由小写英文、数字和指定特定符號(@ . _ . -)。"},
    {"Question":"如何设置用户昵称？","Answer":"用户的昵称是在第一次验证登入时可以设置的，建议最多使用7字符"},
    {"Question":"如何限制指定子渠道用户不能登入游戏应用里？","Answer":"每次用户尝试登入应用的时候，eBET 服务器会向渠道用户验证 API 服务器发送 HTTP POST，渠道 API 验证该用户如果是来自子渠道，建议返回‘渠道维护当中’的状态代码。"},
    {"Question":"如何创建新的用户在 eBET 服务器里？","Answer":"方法一，每次新用户首次登入进 eBET 服务器里，eBET 服务器都会自动创建新的用户账号。 方法二，通过 eBET 提供的 API 接口创建用户。"},
    {"Question":"如果在向 eBet API 服务器 发送充值请求，而因网络问题或者是请求超时，应该如何处理？","Answer":"可以使用userinfo来查询看用户之前和之后的金额是否一样，或使用rechargestatus查询发送的请求已经被处理或否。"},
    {"Question":"如果频密的充值可以吗?","Answer":"不行的，建议1-2分钟，不然ebat服务器会返回系统繁忙导致充值失败。"},
    {"Question":"有几种登入方式？","Answer":"4種 普通登入：用户在eBET的web或app上输入帐号密码，eBET再提供给渠道做验证。 Token登入：用户登入渠道平台后，点击渠道提供的Token登入连结进入eBET web，eBET会提供给渠道做再次验证。 AppLink登入：用户登入渠道平台后，点击渠道提供的AppLink登入并开启eBET app，eBET会提供给渠道做再次验证。 OAuth登入：渠道希望直接使用eBET app却想使用自己的登入页面时，可以使用该登入方式。提供登入页连结并实作相关api。"},
    {"Question":"如何分辨玩家是属于那一个子渠道？","Answer":"您可以使用userInfo这支api来查询。"},
    {"Question":"第一次登入的用户，如何为他们充值，同步渠道和eBet服务器数据库里的用户金额？","Answer":"方法一，每次渠道返回 eBet 服务器用户认证成功后，eBet 服务器会再向渠道的用户验证 API HTTP POST 用户的信息，包括目前用户拥有的金额。这时，渠道系统就可以同步金额，为渠道转出或者转进金额。 方法二，通过 eBET 提供的 API 接口成功创建新用户后，就可以为用户充值。"},
    {"Question":"渠道用户名abc123和ABC123是可以一样？","Answer":"一样的，因为eBET只允许小写英文，系统会自动转成小写。"},
    {"Question":"渠道和子渠道可以用于相同的用户名吗？","Answer":"不行的，因为渠道本身并没有能力去判断该用户是否是从哪一个子渠道。 PS：建议渠道可以添加前缀或是后缀。"},
    {"Question":"渠道商可以定义子渠道的ID吗？","Answer":"不可以，每当创建新的子渠道，系统会自动定义子渠道ID，无法更改。"},
    {"Question":"渠道商的渠道ID，如何得到？","Answer":"当 eBet为渠道商成功开启了渠道之后，就会把渠道 ID 提供给渠道商开发人员知道，以便能进行系统对接。"},
    {"Question":"渠道商要如何创建子渠道？","Answer":"eBET会提供后台及管理员帐号，渠道可以使用该帐号创建子渠道"},
    {"Question":"需要用户名前缀吗？","Answer":"决定权在于渠道，只要渠道 web api 验证没有问题就可以了。"},
    {"Question":"请问可以进行各每个时间端获取用户下注记录？","Answer":"可以。可以根据渠道业务需求设置请求。PS:为了肯定获取数据不会加压我们的 API 组件， 建议每 15 分钟 获取数据，每次返回 1000之内会较好。"},
    {"Question":"请问如何查看只有子渠道的用户下注记录？","Answer":"可以把子渠道参数设为改子渠道 ID 就好。"},
    {"Question":"请问查询用户下注记录的数据是否同步？","Answer":"是同步。实时查询最好是能延后2~3分钟在查询"},
    {"Question":"请问查询用户投注记录，出现乱码用户名？","Answer":"乱码用户名是测试用户的数据，获取投注记录时需要自行过滤。"},
    {"Question":"请问要如何转出和转进用户金额","Answer":"如果要转进，金额转进用户的现有金额里，就设 money 为 100 正数如果要转出，金额从用户的现有的金额转出，就设 money 为 －100 负数"},
    ];

